### ISSUE TITLE
[Feature Request] the ability to run this on a personal server and not replit

### ISSUE THREAD

**Issue by Motzumoto** [eternal404/nitro-sniper#354]
### Is your feature request related to a problem?

I guess its kinda related to a problem - replit is really fucking slow, and my server isnt, would be nice if it was natively supported to run on my server

### Describe the solution you'd like

Id really like to run this on my own hardware

### How will this be beneficial to the sniper

There will be a lot of benefits, speed, security, etc

### Please provide an example of usage of this feature

I believe ive already done this in the previous descriptions

**Comment by eternal404** [comment]
You can already do this?

**Comment by Motzumoto** [comment]
> You can already do this..?

No? when i tried I got this obscure error, i assumed you had made it specifically for replit so i opened this issue

**Comment by eternal404** [comment]
What was the error.

**Comment by Motzumoto** [comment]
> What was the error.

```node
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1334:16)
    at listenInCluster (node:net:1382:12)
    at Server.listen (node:net:1469:7)
    at Function.listen (/home/ubuntu/YourMom/nitro-sniper/node_modules/express/lib/application.js:618:24)
    at Dashboard.attachListeners (/home/ubuntu/YourMom/nitro-sniper/src/lib/Dashboard.js:20:33)
    at Dashboard.start (/home/ubuntu/YourMom/nitro-sniper/src/lib/Dashboard.js:14:10)
    at new Dashboard (/home/ubuntu/YourMom/nitro-sniper/src/lib/Dashboard.js:9:10)
    at init (/home/ubuntu/YourMom/nitro-sniper/src/index.js:50:23)
    at Object.<anonymous> (/home/ubuntu/YourMom/nitro-sniper/src/index.js:106:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1361:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}
```

**Comment by eternal404** [comment]
Your VPS doesnt have an environment variable called PORT set and its using the default port of 3000, this is your own problem.

**Comment by Motzumoto** [comment]
alright thank you
